#!/bin/bash

# Save list of staged Python files
STAGED_PY_FILES=$(git diff --cached --name-only -z | tr '\0' '\n' | grep -E '\.py$' | tr '\n' ' ')

# If there are staged Python files, format them
if [ -n "$STAGED_PY_FILES" ]; then
    echo "Running pre-commit formatting..."
    
    # Run formatting via tox
    poetry install && poetry run tox -p -e black -e isort
    RESULT=$?
    
    if [ $RESULT -ne 0 ]; then
        echo ""
        echo "Pre-commit formatting failed."
        exit 1
    fi
    
    # Re-stage only the originally staged Python files
    git add $STAGED_PY_FILES
    
    echo "Formatting complete."
fi

echo ""
echo "Ready to commit."
exit 0
