export enum SetupScreen {
  Loading,
  Welcome,
  SetupPassword,
  SetupSeedPhrase,
  SetupBackupSigner,
  AgentSelection,
  SetupYourAgent,
  SetupEoaFunding,
  SetupEoaFundingIncomplete,
  SetupCreateSafe,
  Restore,
  RestoreViaSeed,
  RestoreSetPassword,
  RestoreViaBackup,
  AgentIntroduction,
}
