export enum SetupScreen {
  Loading,
  Welcome,
  SetupPassword,
  SetupSeedPhrase,
  SetupBackupSigner,
  SelectYourAgent,
  SetupEoaFunding,
  SetupEoaFundingIncomplete,
  SetupCreateSafe,
  Restore,
  RestoreViaSeed,
  RestoreSetPassword,
  RestoreViaBackup,
}
