# TBA
name: Frontend

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      # Configure Yarn network settings for timeout, retries, and reduced concurrency
      - name: Configure Yarn network settings
        run: |
          yarn config set network-timeout 60000         # Set network timeout to 1 minute
          yarn config set network-retries 10             # Retry up to 10 times
          yarn config set network-concurrency 2          # Reduce concurrency to 2 connections

      # Install dependencies
      - name: Install dependencies
        run: yarn install:frontend

      # Lint and test
      - name: Lint
        run: yarn lint:frontend
      # Test
      # - name: Test
      # run: yarn test:frontend
